- name: "Demonstrate connecting to switches"
  hosts: switches
  connection: ansible.netcommon.network_cli
  gather_facts: false
      
  tasks:
    - name: Teste de conexão
      ansible.netcommon.cli_command:
        command: show version
      register: nxos_version

    - name: Exibir versão do sistema
      debug:
        var: nxos_version.stdout
