- name: "Demonstrate connecting to switches"
  hosts: switches
  connection: ansible.netcommon.network_cli
  remote_user: fabio
  gather_facts: false
      
  tasks:
  - name: run show version on remote devices
    cisco.nxos.nxos_command:
      commands: show version

  - name: run show version and check to see if output contains Cisco
    cisco.nxos.nxos_command:
      commands: show version
      wait_for: result[0] contains Cisco

  - name: run multiple commands on remote nodes
    cisco.nxos.nxos_command:
      commands:
        - show version
        - show interfaces

  - name: run multiple commands and evaluate the output
    cisco.nxos.nxos_command:
      commands:
        - show version
        - show interfaces
      wait_for:
        - result[0] contains Cisco
        - result[1] contains loopback0

  - name: run commands and specify the output format
    cisco.nxos.nxos_command:
      commands:
        - command: show version
          output: json
