---
- name: NXOS_PLAYBOOK
  connection: network_cli
  hosts: switches
  tasks:
    - name: NXOS_VERSION
      nxos_command:
        commands: show version
    - name: NXOS_INTERFACES
      nxos_command:
        commands: show interface brief
    
