---
- name: show version
  hosts: switches
  gather_facts: false

  tasks:
    - name: run multiple commands on remote nodes
      cisco.nxos.nxos_command:
        commands:
          - show version
          - show interfaces

    - name: run multiple commands and evaluate the output
      cisco.nxos.nxos_command:
        commands:
          - show version
          - show interfaces
        wait_for:
          - result[0] contains Cisco
          - result[1] contains loopback0
