---
- name: RouterOS test with network_cli connection
  hosts: sw
  gather_facts: false
  tasks:

  - name: run show version and check to see if output contains Cisco
    cisco.nxos.nxos_command:
     commands: show version
     wait_for: result[0] contains Cisco
